#ifndef GLOBALESFONCTIONS_GLOBAL_H
#define GLOBALESFONCTIONS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GLOBALESFONCTIONS_LIBRARY)
#  define GLOBALESFONCTIONSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GLOBALESFONCTIONSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GLOBALESFONCTIONS_GLOBAL_H
